INSERT INTO dbo.Car (NumberPlate, Make, Model, Colour, PhotoPath) VALUES
('AB12CDE', 'Ford', 'Fiesta', 'Blue', '/static/cars/ab12cde.jpg'),
('XY19ZRT', 'Volkswagen', 'Golf', 'Black', '/static/cars/xy19zrt.jpg'),
('LK67HJP', 'Vauxhall', 'Corsa', 'Red', '/static/cars/lk67hjp.jpg'),
('MN21QWE', 'Toyota', 'Yaris', 'White', '/static/cars/mn21qwe.jpg'),
('PO18ASD', 'BMW', '320i', 'Grey', '/static/cars/po18asd.jpg'),
('TR14FGH', 'Audi', 'A3', 'Silver', '/static/cars/tr14fgh.jpg'),
('GH65JKL', 'Hyundai', 'i10', 'Green', '/static/cars/gh65jkl.jpg'),
('WE70BNM', 'Kia', 'Rio', 'Blue', '/static/cars/we70bnm.jpg'),
('CX16RTY', 'Nissan', 'Micra', 'Yellow', '/static/cars/cx16rty.jpg'),
('ZA22UIO', 'Mercedes', 'A180', 'Black', '/static/cars/za22uio.jpg'),
('ER13PLM', 'Peugeot', '208', 'White', '/static/cars/er13plm.jpg'),
('DF59VBN', 'Honda', 'Civic', 'Red', '/static/cars/df59vbn.jpg'),
('TY68GHN', 'Mazda', 'Mazda3', 'Grey', '/static/cars/ty68ghn.jpg'),
('OP20KJU', 'Skoda', 'Fabia', 'Silver', '/static/cars/op20kju.jpg'),
('QW15ERT', 'Seat', 'Ibiza', 'Blue', '/static/cars/qw15ert.jpg'),
('AS17DFG', 'Renault', 'Clio', 'Purple', '/static/cars/as17dfg.jpg'),
('ZX11CVB', 'Mini', 'Cooper', 'Green', '/static/cars/zx11cvb.jpg'),
('PL69MKO', 'Tesla', 'Model 3', 'White', '/static/cars/pl69mko.jpg'),
('NM23RTF', 'Ford', 'Focus', 'Black', '/static/cars/nm23rtf.jpg'),
('HJ72QAZ', 'Volkswagen', 'Polo', 'Orange', '/static/cars/hj72qaz.jpg');
