INSERT INTO Car
VALUES 
    ('WX01 BHJ', 'BMW', 'M5 comp', 'green', '/static/img/car_photo2.jpg'),
    ('EP18 PLQ', 'Honda', 'Civic', 'yellow', NULL),
    ('EF62 MNS', 'Porsche', '911 gt3 rs', 'black', NULL),
    ('AB12CDE', 'Ford', 'Fiesta', 'Blue', NULL),
    ('XY19ZRT', 'Volkswagen', 'Golf', 'Black', NULL),
    ('LK67HJP', 'Vauxhall', 'Corsa', 'Red', NULL),
    ('MN21QWE', 'Toyota', 'Yaris', 'White', NULL),
    ('PO18ASD', 'BMW', '320i', 'Grey', NULL),
    ('TR14FGH', 'Audi', 'A3', 'Silver', NULL),
    ('GH65JKL', 'Hyundai', 'i10', 'Green', NULL),
    ('WE70BNM', 'Kia', 'Rio', 'Blue', NULL),
    ('CX16RTY', 'Nissan', 'Micra', 'Yellow', NULL),
    ('ZA22UIO', 'Mercedes', 'A180', 'Black', NULL),
    ('ER13PLM', 'Peugeot', '208', 'White', NULL),
    ('DF59VBN', 'Honda', 'Civic', 'Red', NULL),
    ('TY68GHN', 'Mazda', 'Mazda3', 'Grey', NULL),
    ('OP20KJU', 'Skoda', 'Fabia', 'Silver', NULL),
    ('QW15ERT', 'Seat', 'Ibiza', 'Blue', NULL),
    ('AS17DFG', 'Renault', 'Clio', 'Purple', NULL),
    ('ZX11CVB', 'Mini', 'Cooper', 'Green', NULL),
    ('PL69MKO', 'Tesla', 'Model 3', 'White', NULL),
    ('NM23RTF', 'Ford', 'Focus', 'Black', NULL),
    ('HJ72QAZ', 'Volkswagen', 'Polo', 'Orange', NULL),
    ('BP14LZX', 'Ford', 'Ka', 'Silver', NULL),
    ('KM66RHY', 'Volkswagen', 'Passat', 'Grey', NULL),
    ('SJ21WPU', 'Toyota', 'Corolla', 'Blue', NULL),
    ('RV18NMD', 'BMW', 'X1', 'Black', NULL),
    ('HT70FLC', 'Hyundai', 'Tucson', 'White', NULL);
